### ISSUE TITLE
How to make a command action that run another script

### ISSUE THREAD

**Issue by manudss** [slapdash/platform#10]
I am trying to create a local command in powershell, to run an application. 

How can have I run a specific script when selecting one action ? I want to run this specific command : Start-Process -FilePath "C:\Program Files (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE". 

Is it possible ? 

The script that I want to do. But with replace copy, with run command : 
```Powershell
# PowerShell function to list Start Menu Shortcuts
Function Get-StartMenu{
Begin{
$Path = "$Env:ProgramData\Microsoft\Windows\Start Menu\Programs"
$x=0
      } # End of Begin
Process {
$StartMenu = Get-ChildItem $Path -Recurse -Include *.lnk
ForEach($ShortCut in $StartMenu) {
$Shell = New-Object -ComObject WScript.Shell
$Properties = @{
title = $Shortcut.Name
subtitle = $Shell.CreateShortcut($Shortcut).targetpath
action = @{
type = "copy"
value = "Start-Process -FilePath `"$($Shell.CreateShortcut($Shortcut).targetpath)`""
}
moveAction = @{
type = "add-param"
name = $Shortcut.Name
value = $Shortcut.Name
}
}
New-Object PSObject -Property $Properties
$x ++
        } #End of ForEach
[Runtime.InteropServices.Marshal]::ReleaseComObject($Shell) | Out-Null
    } # End of Process
End{

     }
}
#Echo the json command:


Clear-Host
echo "{ 
	`"view`": {
		`"type`": `"list`",
		`"options`":"
Get-StartMenu | Sort ShortcutName | ConvertTo-Json

"	}
}"
```

**Comment by taras-slapdash** [comment]
Hey @manudss! 

Thanks for your question. 

I'm not an expert in PowerShell or Windows but I'll do my best to help you out. 

Today, [Action](https://platform.slapdash.com/reference/command-response-action) doesn't allow you to execute any custom code. We may support something like this in the future but at the moment you can use "add-param" as the main action for your options:

```json
{
  "view": {
    "type": "list",
    "options": [
      {
        "title": "Open Github Shortcut",
        "action": {
          "type": "add-param",
          "name": "shortcut",
          "value": "github_shortcut"
        }
      }
      ...
    ]
  }
}
```

So when the user selects an option, your command (script) will be run with the `shortcut` parameter. The value of this parameter will match the value of the corresponding option. For example, if the user selected "Open Github Shortcut", Slapdash would run your script in the following way:

```
PowerShell -File your-command-script.ps1 --shortcut=github_shortcut
```

Now, in your script, you'd need to check whether the command was run with the `shortcut` parameter. If it was then you would need to match the parameter's value to the actual shortcut and run the respective command. Otherwise, your command should return a List View with options. 

Alternatively, instead of using the shortcut's name as a parameter's value, you can use the file path instead. This may make things simpler for your script. 

In our docs, there is a tutorial for the [Copy Special Character](https://platform.slapdash.com/command-tutorials/copy-special-character) command which demonstrates how a custom parameter is used to run a command. 

I hope it's helpful but please let me know if I misunderstood how your command should work or if you have any questions.

**Comment by manudss** [comment]
Hello, 

Thanks, for your answer. Yes, I have succeeded to make something works. I would like to have something, to run local application. (I think, this features, should be a basics for the desktop version). 

But for powershell command, the call was not done in the correct format. The script was called like this : 

`PowerShell -File your-command-script.ps1 --shortcut=github_shortcut`

But should be called with this format : 
`PowerShell -File your-command-script.ps1 -shortcut github_shortcut`

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2 

It's works me with a workaround by using the args[0] and then replace the params name (.replace('--shortcut=', '') . 

regards.

**Comment by taras-slapdash** [comment]
Glad you found the workaround. 

We opt in to using the same style for passing arguments across all scripts. But it's understandable that in some scripts this will require additional parsing and conversion.

I think in the future we'll have some wrappers and helper functions to reduce the boilerplate code a developer has to write. For instance, we can build functions to parse arguments for each scripting language that we support. 

I noted your feedback. Thank you!
